# For more information, please see https://pixi.prefix.dev/dev/reference/pixi_manifest/

[workspace]
authors = [
    # TODO: Add to group members before Alex
    "Alex Maldonado <alex.maldonado@pitt.edu>"
]
channels = ["conda-forge", "bioconda", "nvidia", "pytorch"]
name = "biosc1640-project"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "26.2.10"

[pypi-dependencies]
lab = { path = ".", editable = true }

[system-requirements]
linux = "4.18"
libc = { family = "glibc", version = "2.28" }
macos = "13.0"

[environments]
dev = ["dev"]

[tasks]

[dependencies]
python = ">=3.12.0,<3.15"
loguru = ">=0.7.3,<1.0"

[feature.dev.dependencies]
ruff = ">=0.15.0,<0.18"
setuptools = ">=82.0.0,<83"
setuptools-scm = ">=9.2.2,<10"
wheel = ">=0.46.3,<0.47"
pytest = ">=9.0.2,<10"
gh = { version = ">=2.87.2,<3", channel = "conda-forge" }
bump-my-version = ">=1.2.7,<2"

[feature.dev.tasks]
format = { cmd = ["ruff", "check", "--select", "I", "--fix", "&&", "ruff", "format", "--config", ".ruff.toml", "./"] }
tests = { cmd = [
    "PYTHONPATH=.",
    "pytest",
    "-c",
    ".pytest.ini",
    "--failed-first",
]}
check-data = "python -u scripts/check.py"
fetch-data = "python -u scripts/fetch.py"
compress-data = "python -u scripts/compress.py"
publish-data = "python -u scripts/publish.py"
bump = { cmd = ["bump-my-version", "bump", "patch"] }
release = { depends-on = ["compress-data", "bump"], cmd = ["git", "push", "--follow-tags", "&&", "pixi", "run", "publish-data"] }

